site_name: Zineb Aissaoui
site_description: >-
  It's my personal website where I share my portfolio and the projects I'm working on. 
docs_dir: web/

# Configuration
theme:
    font: false
    name: material
    logo: 'logo.png'
    favicon: 'logo.png'
    icon:
      previous: fontawesome/solid/angle-left
      next: fontawesome/solid/angle-right
    palette:
      - scheme: default
        primary: black
        media: "(prefers-color-scheme: light)"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        accent: 'indigo'
      - scheme: slate
        media: "(prefers-color-scheme: dark)"
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: black
        accent: 'blue'

    features:
        - navigation.instant
        - content.action.edit
        - content.code.copy
        - content.code.select
        # - announce.dismiss
        - content.code.annotate
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.indexes
        # - navigation.instant
        # - navigation.prune
        #- navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - navigation.expand
        - navigation.footer
        # - toc.integrate
        - navigation.path
        - navigation.indexes
        - content.code.select

    custom_dir: overrides

extra_css:
    - 'stylesheets/extra.css'
    - 'stylesheets/fonts.css'
    - 'stylesheets/home/extra.css'
    - 'stylesheets/home/about.css'

# Customization
extra:
  analytics:
    provider: google
    property: G-4GPL6MXYQ3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our Comments section below.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZinebAissaoui
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zineb-aissaoui/
    - icon: fontawesome/brands/facebook


# Repository
repo_url: https://github.com/ZinebAissaoui/ZinebAissaoui
edit_uri: edit/source/web/

# Copyright
copyright: Copyright &copy; 2024 Zineb Aissaoui


# Extensions
markdown_extensions:
    - meta
    - attr_list
    - codehilite
    - sane_lists
    - admonition
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    # - pymdownx.emoji:
    #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Portfolio: index.md
  - Projects:
    - RAG with Langchain: projects/Academic Projects/RAG with Langchain.md
    - Medical recordes traitment with NLP : projects/Academic Projects/Medical records - NLP.md
    - Realtime Data streaming : projects/Academic Projects/RealtimeDataStreaming.md
  #  - projects/Professional Projects/index.md
  #- ğ€ğœğšğğğ¦ğ¢ğœ ğğ«ğ¨ğ£ğğœğ­ğ¬:
  #     - projects/Academic Projects/index.md
  #     - RAG with Langchain.md: projects/Academic Projects/RAG with Langchain.md

 